### ISSUE TITLE
BURGER MENU > Close it when user is in a category

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#10]
As a user I want the burger menu to close itself so I can navigate in the category I selected and not be intruded by its presence.

CURRENTLY
<img width="1440" alt="capture d ecran 2018-05-16 a 15 44 53" src="https://user-images.githubusercontent.com/39262841/40120691-1e53e05e-5920-11e8-8f62-8b0c74f0db39.png">
Burger Menu stays open until you close it even if you already clicked inside the section you selected

SHOULD BE
Once you clicked inside the selected section, burger menu should close itself

**Comment by mikbry** [comment]
Ok we should temporary Drawer instead of permanent one.

**Comment by mikbry** [comment]
https://github.com/Zoapp/front/issues/80
