### ISSUE TITLE
CREATE FORM> Confirmation account creation

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#11]
As a user I want to know if the account I just created is valid so that I can connect to the tool and start creating my chatbot

CURRENTLY
Once the form is completed, "brutal" redirection to the connexion page with no confirmation of the account creation

SHOULD BE
Add a message to the connexion page once the account is created saying something like "your account <name> has been created, you can now connect with this page and create your bot!"

**Comment by mikbry** [comment]
This issue was moved to Opla/opla#15
