### ISSUE TITLE
CREATE FORM> Mail address is not verified

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#12]
as a user I want to create an account with my valid mail address so I can connect to the tool later and start my bot

CURRENTLY
Seems to be no control on validity for mail
I added a completely random mail and the account is created anyway

SHOULD BE
Add mail verification to see if entered mail is valid 
(+ I don't seem to see an email sent for confirmation neither)

**Comment by mikbry** [comment]
Related to
https://github.com/Zoapp/backend/issues/29
