### ISSUE TITLE
CONNECTED SCREEN> Cosmetic> wording spacing

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#14]
some spacings in the texts are missing :  
 - For example:send
 - An intentis an
 - intent's inputwith

**Comment by mikbry** [comment]
could you make screenshot and highlight areas

**Comment by julieopla** [comment]
<img width="752" alt="capture d ecran 2018-05-17 a 10 58 49" src="https://user-images.githubusercontent.com/39262841/40167497-7cb9ed7c-59c1-11e8-9764-c908201596d3.png">
