### ISSUE TITLE
[urgent]BUILDER> Create input/output> can't edit after an "any" an entity or code

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#24]
As a user I want to write an input/output containing functions like any / entity / code in order to integrate my chatbot.

CURRENTLY
Once a  any / entity / code added you can't add any text next to it (inline and pop up window for edition)
<img width="730" alt="capture d ecran 2018-05-17 a 15 56 11" src="https://user-images.githubusercontent.com/39262841/40182066-d7e1c188-59ea-11e8-8ac6-f68035cabe98.png">

SHOULD BE 
You should be able to point and add text and / or items anywhere before, between and after items

**Comment by lodelestra** [comment]
#### Debug notes:
For this intent input
<img width="343" alt="screen shot 2018-05-19 at 16 21 53" src="https://user-images.githubusercontent.com/10141712/40269591-d4dd2904-5b80-11e8-9972-639c08239d33.png">
When you try to select the end of the sentence, actionsEditable.HandleFocus() is called 4 times targeting: span end, span any, span end and span any again.
I have a patch but I need to check for side effects.
