### ISSUE TITLE
BUILDER>Import> French text 

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#27]
CURRENTLY
<img width="844" alt="capture d ecran 2018-05-18 a 10 09 24" src="https://user-images.githubusercontent.com/39262841/40223529-aa596614-5a83-11e8-9b86-fc5086116479.png">
Some items are in french language

SHOULD BE
Put that text in english

**Comment by mikbry** [comment]
This issue was moved to Opla/opla#10
