### ISSUE TITLE
GLOBAL> Invert SAVE-CANCEL buttons for UX purpose

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#28]
CURRENTLY
<img width="844" alt="capture d ecran 2018-05-18 a 10 09 24" src="https://user-images.githubusercontent.com/39262841/40224235-d3eb9964-5a85-11e8-8f20-62021ab9cb44.png">
<img width="757" alt="capture d ecran 2018-05-18 a 10 23 33" src="https://user-images.githubusercontent.com/39262841/40224236-d40af6e2-5a85-11e8-821a-cfa9576d5350.png">
<img width="932" alt="capture d ecran 2018-05-18 a 10 23 42" src="https://user-images.githubusercontent.com/39262841/40224237-d42215f2-5a85-11e8-821d-2586ec10af49.png">
Positioning of the buttons in every validation / cancellation is VALIDATION first and then CANCELLATION
It's a bit confusing for the user for UX matters, usually CANCEL is first and OK .

SHOULD BE 
- Exchange buttons order CANCEL - SAVE
- Make CANCEL different graphically (maybe less bold) so the difference between the actions can look clearer 
- in BUILDER inputs / outputs, instead of CHANGE, writing SAVE may be clearer

**Comment by mikbry** [comment]
This issue was fixed here:
https://github.com/Opla/front/issues/117
