### ISSUE TITLE
BUILDER> Unable to delete an output

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#31]
CURRENTLY
When you have created an output and if it is the only one of the list or the second one of the list, there are no recycle bin that appear to delete it
<img width="1440" alt="capture d ecran 2018-06-12 a 09 16 43" src="https://user-images.githubusercontent.com/39262841/41275586-a0daf024-6e21-11e8-96d7-9979a18ca09f.png">
<img width="1440" alt="capture d ecran 2018-06-12 a 09 16 35" src="https://user-images.githubusercontent.com/39262841/41275589-a27c830c-6e21-11e8-9156-e5b447f8a3cf.png">
<img width="1440" alt="capture d ecran 2018-06-12 a 09 16 19" src="https://user-images.githubusercontent.com/39262841/41275590-a3840aae-6e21-11e8-8d17-f7cafe4f7973.png">

SHOULD BE
Every output / input should be deletable

**Comment by lodelestra** [comment]
cf #40
