### ISSUE TITLE
BUILDER> Input / Output are not pre-saved if you don't click the arrow 

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#32]
CURRENTLY
When you enter an output / input in the builder and you get out of the intent you were in, when you get back on that intent, the output/input are deleted because you didn't click on the arrow to save them
<img width="1440" alt="capture d ecran 2018-06-12 a 09 24 22" src="https://user-images.githubusercontent.com/39262841/41276002-1201fd96-6e23-11e8-9f95-e5bc45e2190a.png">
<img width="1440" alt="capture d ecran 2018-06-12 a 09 24 34" src="https://user-images.githubusercontent.com/39262841/41276004-1323fae4-6e23-11e8-8904-1fb44c9be042.png">

SHOULD BE
The builder should keep the input / output so you can save them even after you went in an other intent

**Comment by lodelestra** [comment]
cf #40
