### ISSUE TITLE
BUILDER> Deleting slashes in user's answers

### ISSUE THREAD

**Issue by julieopla** [Opla/community-edition#37]
CURRENTLY
When the chatbot has to hold back the information of a date, it deletes the slashes in between numbers
<img width="411" alt="capture d ecran 2018-06-14 a 10 05 49" src="https://user-images.githubusercontent.com/39262841/41399452-aec04730-6fba-11e8-81cb-3a8aecb2a3f4.png">

SHOULD BE
As in previous version, keep what the user entered
<img width="402" alt="capture d ecran 2018-06-14 a 10 06 16" src="https://user-images.githubusercontent.com/39262841/41399475-bc2d5c32-6fba-11e8-9f34-9b597aeaa5f3.png">

**Comment by mikbry** [comment]
I can't reproduce it

**Comment by julieopla** [comment]
reproduced right now
<img width="404" alt="capture d ecran 2018-06-14 a 16 14 18" src="https://user-images.githubusercontent.com/39262841/41417578-10894e98-6fee-11e8-9b2f-40ced6e42b9e.png">

to reproduce in master version, id ; test1406 / password : 1234
try mode opératoire REJ012 / cessation au statut édité and go to the step where the chatbot asks you a date d'effet souhaitée
